[project]
name = "ai2048"
version = "0.1.0"
description = "silly game gets beat by neural networks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "torch>=2.6.0",
]
